### ISSUE TITLE
希望能尽快release出1.4.3版本

### ISSUE THREAD

**Issue by 0x112** [teddysun/xray-plugin#11]
看来新版本支持了grpc, 希望能尽快释出。。。

**Comment by mazzz1y** [comment]
我也等不及grpc特征!

**Comment by teddysun** [comment]
莫急。在等上游更新。

**Comment by teddysun** [comment]
Rebuild version v1.4.2 
https://github.com/teddysun/xray-plugin/releases/tag/v1.4.2
