### ISSUE TITLE
Question:how to disable MUX

### ISSUE THREAD

**Issue by sophauer** [teddysun/xray-plugin#14]
as tittle,
i tried mux=false but it showed "failed to parse mux, use default value"

**Comment by mazzz1y** [comment]
https://github.com/teddysun/xray-plugin/blob/main/main.go#L145

```
mux=0
```

**Comment by sophauer** [comment]
> https://github.com/teddysun/xray-plugin/blob/main/main.go#L145
> 
> ```
> mux=0
> ```

million tKS
