### ISSUE TITLE
Add uTLS option to xray-plugin

### ISSUE THREAD

**Issue by Ka6k** [teddysun/xray-plugin#17]
Please add **uTLS** feature ASAP due to internet censorship based on **TLS fingerprint** in some countries.
#https://github.com/net4people/bbs/issues/139

**Comment by wangzan200808** [comment]
没人回复吗？

**Comment by lxhao61** [comment]
希望同时加上Shadowsocks+gRPC+uTLS+REALITY应用（Xray 版本不小于 v1.8.0 才支持 REALITY），即gprc-reality选项配置。

**Comment by libertad0101** [comment]
Hi! Any updates?
