### ISSUE TITLE
请问这个插件与v2ray-plugin功能有什么区别呢

### ISSUE THREAD

**Issue by triaqu** [teddysun/xray-plugin#2]
我的v2ray-plugin是放在caddy后面，也就是用WS转发SS.
如果xray-plugin也只是这样用，两个插件就没什么区别吧？

**Comment by tianlichunhong** [comment]
是的，我也不清楚。因为感觉也就是加个tls的功能。并不能像xray一样，判断是https的内容，直接不加密转发。因为ss在前面已经进行加密转发了。所以两者到达有什么区别？不过使用感觉，还是xray-plugin要快一些，心理作用？
