### ISSUE TITLE
xray-plugin支持HTTPUpgrade吗？怎么写？

### ISSUE THREAD

**Issue by PHCSJC** [teddysun/xray-plugin#23]
xray-core v1.8.9官方支持了HTTPUpgrade传输方式，可以用来套CDN

大佬的插件也更新到v1.8.9了，那xray-plugin支持HTTPUpgrade吗？写法是什么呢？

**Comment by PHCSJC** [comment]
我试了下：mode=HTTPUpgrade
提示：main: failed to parse config > main: unsupported mode:HTTPUpgrade

**Comment by lxhao61** [comment]
HTTPUpgrade 应该全小写吧。

**Comment by fluggelgleckheimlen** [comment]
HTTPUpgrade is not available in the code, so you can't enable it:
https://github.com/teddysun/xray-plugin/blob/96a75e491a3400935fa58861ad4342027cddd4e0/main.go#L34-L38
